"""
decode.py  —  tokens.txt  ->  out.mid   (the inverse of encode.py)

Reads the single line of tokens back, turns each R:/L: token into a note with a
pitch and a time, and writes a playable MIDI file. Prints the data running in
reverse so you can watch 1-D tokens become 2-D notes again.

Then VERIFIES the round trip: re-reads the original file and checks that every
(hand, step, pitch) survived. Our tokens store onset + pitch + hand, NOT exact
note length, so we compare on exactly that. Note durations are regenerated by
the grid convention below.

Run:  python decode.py               (writes out.mid, verifies vs furelise.mid)
      python decode.py tokens.txt furelise.mid
"""
import sys
import mido

TICKS_PER_BEAT = 480          # same ruler the original used
GRID_DEN = 4                  # sixteenth-note grid
GRID = TICKS_PER_BEAT // GRID_DEN      # 120 ticks per step
GAP = 7                       # tiny lift so repeated notes retrigger (cosmetic)
NOTE_LEN = GRID - GAP         # each note fills its slot minus a short gap
TEMPO = 1_000_000             # microseconds per beat = 60 BPM (matches source)
VELOCITY = 64
RH, LH = 0, 1


def parse_token(tok):
    """'R:76' -> ('R', [76]) ; 'L:.' -> ('L', []) ; 'R:60+69' -> ('R', [60,69])"""
    hand, body = tok.split(":")
    if body == ".":
        return hand, []
    return hand, [int(p) for p in body.split("+")]


def load_columns(path):
    """tokens.txt -> list of (step, [rh pitches], [lh pitches])."""
    line = open(path, encoding="utf-8").read().strip()
    tokens = line.split()
    columns = []
    # tokens come in R,L pairs: step s is tokens[2s], tokens[2s+1]
    for step, i in enumerate(range(0, len(tokens), 2)):
        _, rh = parse_token(tokens[i])
        _, lh = parse_token(tokens[i + 1])
        columns.append((step, rh, lh))
    return tokens, columns


def columns_to_events(columns):
    """(step, rh, lh) -> flat list of (hand, step, pitch) note events."""
    events = []
    for step, rh, lh in columns:
        for p in rh:
            events.append((RH, step, p))
        for p in lh:
            events.append((LH, step, p))
    return events


def build_track(events_for_hand, name, with_tempo):
    """One hand's (step, pitch) events -> a mido MidiTrack with correct timing."""
    track = mido.MidiTrack()
    track.append(mido.MetaMessage("track_name", name=name, time=0))
    if with_tempo:
        track.append(mido.MetaMessage("time_signature", numerator=3, denominator=8, time=0))
        track.append(mido.MetaMessage("key_signature", key="C", time=0))
        track.append(mido.MetaMessage("set_tempo", tempo=TEMPO, time=0))

    # make absolute-time on/off events, then sort (note_off before note_on at a tie)
    abs_events = []
    for step, pitch in events_for_hand:
        on = step * GRID
        abs_events.append((on, 1, pitch))                 # 1 = note_on
        abs_events.append((on + NOTE_LEN, 0, pitch))       # 0 = note_off
    abs_events.sort(key=lambda e: (e[0], e[1]))            # off (0) sorts before on (1)

    prev = 0
    for abs_tick, kind, pitch in abs_events:
        delta = abs_tick - prev
        prev = abs_tick
        if kind == 1:
            track.append(mido.Message("note_on", note=pitch, velocity=VELOCITY, time=delta))
        else:
            track.append(mido.Message("note_off", note=pitch, velocity=0, time=delta))
    return track


# ---------- round-trip verification against the original MIDI ----------
def read_original_events(path):
    """Original .mid -> set of (hand, step, pitch), snapped the same way encode does."""
    mid = mido.MidiFile(path)
    got = set()
    for hand, track in ((RH, mid.tracks[0]), (LH, mid.tracks[1])):
        t = 0
        for msg in track:
            t += msg.time
            if msg.type == "note_on" and msg.velocity > 0:
                got.add((hand, round(t / GRID), msg.note))
    return got


def main(tokens_path, original_path):
    tokens, columns = load_columns(tokens_path)
    print(f"read {tokens_path}: {len(tokens)} tokens -> {len(columns)} grid columns\n")

    print("STAGE 4' — pair tokens back into columns, first 8:")
    for step, rh, lh in columns[:8]:
        print(f"    step {step:3d}   R:{rh if rh else '.'}   L:{lh if lh else '.'}")

    events = columns_to_events(columns)
    print(f"\nSTAGE 2' — expand to {len(events)} note events (hand, step, pitch), first 8:")
    for hand, step, p in events[:8]:
        print(f"    {'R' if hand==RH else 'L'}  step {step:3d}  pitch {p}")

    rh_events = [(s, p) for h, s, p in events if h == RH]
    lh_events = [(s, p) for h, s, p in events if h == LH]

    print("\nSTAGE 1' — note events become MIDI note-ons at absolute ticks, first 8 (right hand):")
    for s, p in rh_events[:8]:
        print(f"    tick {s*GRID:5d}   note_on pitch {p}   (off at {s*GRID+NOTE_LEN})")

    mid = mido.MidiFile(ticks_per_beat=TICKS_PER_BEAT)
    mid.tracks.append(build_track(rh_events, "Piano", with_tempo=True))
    mid.tracks.append(build_track(lh_events, "Piano", with_tempo=False))
    mid.save("out1.mid")
    print(f"\nwrote out.mid  ({len(rh_events)} right-hand + {len(lh_events)} left-hand notes)")

    # ---- the important part: prove nothing was lost ----
    print("\n===== ROUND-TRIP VERIFY (compare to original) =====")
    rebuilt = {(h, s, p) for h, s, p in events}
    try:
        original = read_original_events(original_path)
    except FileNotFoundError:
        print(f"(original {original_path} not found — skipping verify)")
        return
    if rebuilt == original:
        print(f"PASS — all {len(original)} (hand, step, pitch) events match exactly.")
        print("Encoding is lossless for onset + pitch + hand. Durations are grid-regenerated.")
    else:
        missing = original - rebuilt
        extra = rebuilt - original
        print(f"MISMATCH — {len(missing)} missing, {len(extra)} extra.")
        for e in list(missing)[:5]:
            print("   missing:", e)
        for e in list(extra)[:5]:
            print("   extra:  ", e)


if __name__ == "__main__":
    tokens_path = sys.argv[1] if len(sys.argv) > 1 else "tokens.txt"
    original_path = sys.argv[2] if len(sys.argv) > 2 else "furelise.mid"
    main(tokens_path, original_path)